### ISSUE TITLE
Add option to configure AppUserId from Initialize

### ISSUE THREAD

**Issue by MoienTajik** [Kebechet/Maui.RevenueCat.InAppBilling#40]
Currently `Initialize` method in `RevenueCatBillingiOS` (I'm not sure about Android impl detail) doesn't accept `AppUserId`, but `Purchases.ConfigureWithAPIKey` accepts that parameter and we can initialize the `AppUserId` from startup instead of doing that via `Login`.

**Comment by Kebechet** [comment]
So If I understand this correctly you would like to have 2 methods:
current one: `Initialize(string apiKey)` and
new one: `Initialize(string apiKey, string appUserId)`

Correct ?

**Comment by MoienTajik** [comment]
Yes, exactly. This way, we can initialize the plugin using `appUserId` in first place in the DI, and as far as I understood, that doesn't need to be async unlike the Login method.

**Comment by Kebechet** [comment]
This month I am quite busy so I wont be able to implement this. But feel free to create a PR

**Comment by Kebechet** [comment]
Ok I got to that sooner because I needed to adjust one thing.

Your proposal was Implemented in:
https://github.com/Kebechet/Maui.RevenueCat.InAppBilling/commit/772a40375b011c884ea0940c3c9262cf4d23db95

and will be released as [v4.5.0](https://www.nuget.org/packages/Kebechet.Maui.RevenueCat.InAppBilling/4.5.0)

**Comment by Kebechet** [comment]
@MoienTajik does it work correctly ?
